### ISSUE TITLE
Get multiple data per requests

### ISSUE THREAD

**Issue by azukaar** [CyclopsMC/IntegratedREST#13]
#### Issue type:

- :question: Question

____

#### Question:

Hello! I'm having a lot of fun building up my API, *but* one massive issue is that I need (AFAIU) to build a proxy block + a variable card for each values I want to GET, and then GET them separatly.
I was wondering if it was possible to GET a reader block directly and retrieve a JSON containing all the variables that reader has.
I know it's possible to query a reader but it just retrieves generics info about it and no values. Am I missing something? 

Thanks lot !

**Comment by rubensworks** [comment]
> GET a reader block directly

That is not possible unfortunately.
This is because values can only be evaluated when they have an active variable somewhere (writers, display panels, ...). Since readers don't do anything by themselves actively, they can not be read by this mod.

You can GET any writer or display panel though.
