### ISSUE TITLE
Server process does not stop

### ISSUE THREAD

**Issue by Cheeseypop** [CyclopsMC/IntegratedREST#14]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The server process does not exit after the stop command has been run and saving completed.

Modlist:
CommonCapabilities-1.16.4-2.5.5.jar
CyclopsCore-1.16.4-1.9.3.jar
IntegratedDynamics-1.16.4-1.1.21.jar
IntegratedREST-1.16.4-1.1.1.jar

Default configs

I left the server in the half-stopped state for over 7 hours with no change.

#### Steps to reproduce the problem:

1. Install the mod
2. Start the server (existing or new world)
3. Stop the server

#### Expected behaviour:

Server process to exit after saving has been completed.

____

#### Versions:

- This mod: 1.16.4-1.1.1
- Minecraft: 1.16.4
- Forge: 1.16.4-35.1.28
- Also tested on forge 35.1.13

#### Log file:

https://pastebin.com/hP25kxZ1 Nothing out of the ordinary

**Comment by rubensworks** [comment]
Thanks for reporting!
