### ISSUE TITLE
SP Game crash when running server

### ISSUE THREAD

**Issue by RGFTheCoder** [CyclopsMC/IntegratedREST#15]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The game will crash when running this mod if there is a minecraft server running with the mod as well due to both of them trying to use the default port.

#### Steps to reproduce the problem:

1. Make a forge 1.16.5 server with this mod
2. Run a client with this mod
3. Try to join a local world

#### Expected behaviour:

The game should give a warning (maybe in chat) about not being able to bind the port, but not crash. On servers, it should print an error message to the console, but not crash.

____

#### Versions:

- This mod: 1.1.3
- Minecraft: 1.16.5
- Forge: 36.1.4

#### Log file:

https://pastebin.com/SMRPqqwR

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The crash is intentional, as the mod can not function otherwise. You can change the port in the config file.
