### ISSUE TITLE
[1.16.5]The Boolean value of the proxy cannot be modified to true using the command provided by wiki.

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedREST#16]
#### Issue type:

- :question: Question 

____

#### Question:

version:
1. IntegratedREST-1.16.5-1.1.3
2. IntegratedDynamics-1.16.5-1.8.4
3. CommonCapabilities-1.16.5-2.7.0
4. CyclopsCore-1.16.5-1.11.6

Command tried: 
1. curl -X POST -d '{"value":true}' http://localhost:3000/networkElement/integratedrest/http/0
2. curl -X POST -d '{"value":true}' http://localhost:3000/networkElement/integrateddynamics/http/0

![image](https://user-images.githubusercontent.com/80253667/121809328-f7d0a300-cc8e-11eb-9094-06e25ee0812a.png)
![image](https://user-images.githubusercontent.com/80253667/121809338-fdc68400-cc8e-11eb-88a7-8be86bb7bfe1.png)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Your `curl` command seems to be throwing CLI arg parsing errors.
Those example commands are for Unix systems, while you seem to be using Windows.
I'm no Windows user myself, but I suspect Windows interprets single-quotes incorrectly.
I would suggest writing the `-d` value within double quotes, for which you'll probably have to escape the double quotes within the JSON data block.

**Comment by GaN8373** [comment]
> Your `curl` command seems to be throwing CLI arg parsing errors.
> Those example commands are for Unix systems, while you seem to be using Windows.
> I'm no Windows user myself, but I suspect Windows interprets single-quotes incorrectly.
> I would suggest writing the `-d` value within double quotes, for which you'll probably have to escape the double quotes within the JSON data block.

Thank you, I can use it normally.
But I encountered a problem, @id is different from the MODID pointed to by the command.
The @id of this http proxy is integratedrest/http/0. The instruction needs to point to /integrateddynamics/http/0.
Is the design so?

**Comment by rubensworks** [comment]
Yep, looks wrong indeed, fixed!
