### ISSUE TITLE
Cannot GET from a display panel when the variable card inside it has NBT data

### ISSUE THREAD

**Issue by Waoweens** [CyclopsMC/IntegratedREST#18]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you put a variable card that contains NBT data inside a display panel, the display panel's /part page will refuse to load.

#### Steps to reproduce the problem:

1. Place a chest
2. Place a block reader facing the chest
3. Connect the block reader and a display panel to a HTTP Proxy
4. Apply "Tile Entity NBT" (from the block reader) to a variable card
5. Place variable card inside display panel
6. Open http://localhost:3000/networkElement/integrateddynamics/part/# in your browser (replace # with your display panel's part number)
7. See that the page does not load

#### Expected behaviour:

Page loads and the NBT data is there.

____

#### Versions:

- Common Capabilities: 1.16.5-2.7.0
- Cyclops Core: 1.16.5-1.11.9
- Integrated Dynamics: 1.16.5-1.9.4
- Integrated REST: 1.16.5-1.1.3
- Minecraft: 1.16.5
- Forge: 36.2.4

#### Log file:

https://gist.github.com/Waoweens/ecdd05f7c8f157c0ab2d3ae5abfee366

**Comment by rubensworks** [comment]
Thanks for reporting!
