### ISSUE TITLE
Add Access-Control-Allow-Origin header to response

### ISSUE THREAD

**Issue by Waoweens** [CyclopsMC/IntegratedREST#19]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

I am trying to GET from a part (using fetch) but the browser seems to block it because of CORS.
Adding the `Access-Control-Allow-Origin` header to the response should fix this.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by Waoweens** [comment]
Any update on this?

**Comment by rubensworks** [comment]
A PR is definitely welcome!
