### ISSUE TITLE
Variables referencing HTTP variables do not get updated

### ISSUE THREAD

**Issue by LucunJi** [CyclopsMC/IntegratedREST#21]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1.Place a HTTP Proxy, select some variable type (such as boolean), and put a variable inside so the variable is linked up with the proxy.
2. Do some computation with the previous variable and get a new variable.
3. Insert the HTTP variable and the new variable into separate screens to monitor their value.
4. Update the HTTP variable by sending something in Postman, Python, or whatever.
5. The HTTP variable gets updated, but the variable referencing it does not.

#### Expected behaviour:

Variables referencing HTTP variables are updated when the referenced variables are updated via HTTP requests. 

____

#### Versions:

- This mod: 1.1.4
- Minecraft: 1.16.5
- Forge: 36.2.0

**Comment by rubensworks** [comment]
Thanks for reporting!
