### ISSUE TITLE
Exception in server tick loop Address already in use

### ISSUE THREAD

**Issue by blacksythe** [CyclopsMC/IntegratedREST#22]
#### Issue type:

- :bug: Bug 

____

Causing server tick loop when loaded as part of the Encrypted_ Modpack

See crash reports, log and debug log

1. ...

Boot Server with encrypted_ modpack in a linux environment (windows untested)
(SP windows works fine)

____

IntegratedREST-1.18.2-1.1.5

- This mod: IntegratedREST-1.18.2-1.1.5
- Minecraft: 18.2
- Forge: 40.1.74

Reported to modpack author as well.
[latest.txt](https://github.com/CyclopsMC/IntegratedREST/files/9440567/latest.txt)

[debug excert.txt](https://github.com/CyclopsMC/IntegratedREST/files/9440568/debug.excert.txt)

[crash-2022-08-28_17.46.45-server.txt](https://github.com/CyclopsMC/IntegratedREST/files/9440570/crash-2022-08-28_17.46.45-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Address already in use

This means that port 3000 (which the IR service runs on), is already bound. Either change the port in the config file, or disable the service to fix it.
