### ISSUE TITLE
Rest block crashes on inserting a blank variable card

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [CyclopsMC/IntegratedREST#25]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Rest block crashes on inserting a blank variable card

#### Steps to reproduce the problem:

Above

#### Expected behaviour:

Whatever the mod is supposed to do
____

#### Versions:

- This mod: IntegratedREST-1.19.4-1.1.8.jar
- Minecraft: client-1.19.4
- Forge: forge-1.19.4-45.0.55

#### Log file:

https://pastebin.com/dqXRTVq3

**Comment by rubensworks** [comment]
Thanks for reporting!
