### ISSUE TITLE
Server crashes on Post request, works in SP

### ISSUE THREAD

**Issue by MakiRollDev** [CyclopsMC/IntegratedREST#27]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I built the proxy. I took a bunch of attempts to post a variable to it, but it worked.
Then I switched it to "any" type, tried it again, but every time since then it caused the server to crash (Due to timeout (60s Tick)).

I downloaded the world and loaded it in single player (changed my URL to localhost) and ran it without issue.

#### Steps to reproduce the problem:

_Note: I am pretty sure this is not enough to recreate the bug in any world, but I don't have the resources to try_
1. Start server
2. Send POST request
3. Game crashes

#### Expected behaviour:

Variable updates like first time/in SP.
____

#### Versions:

- This mod: 1.1.10
- Minecraft: 1.20.1
- Forge: 47.2.17

I will try to recreate this issue with a smaller set of mods if I have the time. 
However, for now I want to note that when trying to GET some data, they did not load/took incredibly long to load (most prominently, the networkElement subpage). The biggest network on the server is around 90 cables and probably 25 connected elements in case that may be the issue.

Total stats:
Number of networks: 8
Sum of all cables: 169
Sum of elements: 86

#### Log file:

https://pastebin.com/A6nZD3Mk

Again, sorry for not having the smallest mod subset, I'm very pressed for time atm and the main priority was to get the Server back up and running.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I see no mentions of this mod or related mods in your stacktrace.
Are you sure you've posted the correct file, and are you sure the crash is not caused by another mod?

**Comment by MakiRollDev** [comment]
Almost 100%. The crashes occurred every time someone tried to POST a value to the http proxy and everything is going smoothly since telling people they can't use it for now.

Regarding the crash file: there does not seem to be an exception or similar anywhere, the server just stops responding and after a minute the watchdog kills it.

I'll probably have time tomorrow to check if it can be reproduced in a different world and/or with less mods.
