### ISSUE TITLE
Output cannot be automatically parsed as json/jsonld

### ISSUE THREAD

**Issue by thunfisch987** [CyclopsMC/IntegratedREST#28]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When fetching from the api the content-type is `text/plain`

#### Steps to reproduce the problem:

1. `curl -i URL_TO_API`
2. check `content-type`

#### Expected behaviour:

The `content-type` is application/ld+json
____

#### Versions:

- This mod: all
- Minecraft: all
- Forge: all

**Comment by rubensworks** [comment]
Thanks for reporting!
