### ISSUE TITLE
GET position player

### ISSUE THREAD

**Issue by NightmareTotoro** [CyclopsMC/IntegratedREST#30]
#### Issue type:

- :question: Question 

____

#### Question:

As suggested on the mod page, I tried to do a GET
"Show the positions of all online players in the overworld on your website" but there is nothing on the wiki, am I doing something wrong or has it not been implemented yet?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
You should be able to use a reader to get all players, and get the coordinates using operators.
Does this help?

**Comment by NightmareTotoro** [comment]
But to do a GET of this variable plate, where would it be?

**Comment by rubensworks** [comment]
You have to put your variables in a writer or display panel, and then GET those parts.
