### ISSUE TITLE
can not request successful "http://localhost:3000/networkElement"

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedREST#35]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Only this networkElement Interface is not normal
load mods:
![image](https://github.com/user-attachments/assets/cb21ca9a-9bae-4ced-85b7-da9c57a463e4)

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 1.1.12-129
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.81

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
That URL requires a network element id, such as `http://localhost:3000/networkElement/123` if your network element id is `123`.

**Comment by GaN8373** [comment]
In the past, I could access the public components on the network by visiting this page. Has this function been cancelled? How can I know exactly what components are on the network?

**Comment by rubensworks** [comment]
Ah no, you're right, that should be possible indeed.
How are you executing the request exactly? And what response are you getting exactly?

**Comment by GaN8373** [comment]
> Ah no, you're right, that should be possible indeed. How are you executing the request exactly? And what response are you getting exactly?

use postman and brower get request, the endpoint no resp. the effect look a.. connect failed

**Comment by GaN8373** [comment]
[saves.zip](https://github.com/user-attachments/files/18235807/saves.zip)
[debug.log](https://github.com/user-attachments/files/18235810/debug.log)
[latest.log](https://github.com/user-attachments/files/18235811/latest.log)
