### ISSUE TITLE
How to get data

### ISSUE THREAD

**Issue by matyklug18** [CyclopsMC/IntegratedREST#5]
#### Issue type:

- :question: Question

____

#### Question:

how i can get data from network, for example, from redstone reader?

**Comment by rubensworks** [comment]
Easy :-)
Just plop down your part (i.e. redstone reader), check the id of the part, and go to `http://localhost:3000/networkElement/integrateddynamics/part/<yourpartid>`.

**Comment by matyklug18** [comment]
and how to get the part id?

**Comment by rubensworks** [comment]
Either check the WAILA/TOP tooltip if you have either of those installed, or break (and replace) the part to get the part id via its item tooltip in your inventory.

**Comment by matyklug18** [comment]
don't work for me :( i don't see that value anywhere

**Comment by rubensworks** [comment]
> don't work for me :(

If you'd specify what doesn't work for you, then I'd be able to help.

**Comment by matyklug18** [comment]
where the value may show?

**Comment by rubensworks** [comment]
The ID is shown in the item or block tooltip when hovering over it.

**Comment by matyklug18** [comment]
yeah, it is 4, but i do not see the value from the reader in that json.
it looks like this:
https://pastebin.com/EkWS6kXD
and i power it with power 14, but no 14 here...

**Comment by rubensworks** [comment]
Ah, but that's because it's a reader, which has a bunch of different values.

What you want instead, is to write one of those aspects to a variable card, and insert that into any other part (like a writer or proxy), and check the JSON output of that part.

The reason for this is that the JSON output only outputs a single value (as done by a writer or proxy), while readers would show multiple values.

**Comment by matyklug18** [comment]
if i enter id of proxy where is the card: error": "Resource was not found."
but writer work for me, THANKS!

**Comment by rubensworks** [comment]
Is the proxy attached to a cable. Can you show a screenshot of your setup?

Maybe there is a bug with the proxy. Perhaps you can try a writer instead.

**Comment by matyklug18** [comment]
while messing with it, i found bug: variable storage voids variable cards. (when i try to program logic with http proxy) anyway, here is the screenshot
![2018-10-29_15 36 39](https://user-images.githubusercontent.com/32399575/47657064-aa13d480-db90-11e8-874e-680471a40b1f.png)

**Comment by rubensworks** [comment]
Oh, that's not good. Could you report a separate issue for this with step-by-step how to reproduce this?

**Comment by matyklug18** [comment]
yep.

**Comment by matyklug18** [comment]
anyway, whats wrong with the proxy?

**Comment by rubensworks** [comment]
No idea, last time I checked it worked, but apparently it doesn't for you.
