### ISSUE TITLE
voiding variable store

### ISSUE THREAD

**Issue by matyklug18** [CyclopsMC/IntegratedREST#6]
#### Issue type:

- :bug: Bug

____

#### Short description:

i put variable carts to variable store while playing with http proxy, trying to get some logic with it. while putting cards into variable store, they aren't visible in system(proggrammed cards do not work), and they dissaper.and it crashed in 3 try to get it work and my test world is corrupted.
#### Steps to reproduce the problem:

1. create number card from http proxy
2. create integer card in proggramer
3. create equals logic.
4. put that card in some writer
5. put the cards inside variable storage
6. play with them
7. and they will dissapear.
8. and world can crash

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by matyklug18** [comment]
ok

**Comment by rubensworks** [comment]
I can not reproduce this with the provided information.

Everything works fine for me, and nothing crashes.

If you have any more details on your issue, be sure to let me know.
